# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SimpleSquareSynth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for SimpleSquareSynth
  pod 'AudioKit'
end
